export type AvitaColorType = {
    red: string
    redOrange: string
    orange: string
    orangeYellow: string
    yellow: string
    yellowGreen: string
    lime: string
    green: string
    cyan: string
    teal: string
    blue: string
    navy: string
    blueViolet: string
    violet: string
    magenta: string
    magentaPink: string
    purple: string
    pink: string
    redPink: string
    brown: string
    tan: string
    beige: string
    maroon: string
    olive: string
    silver: string
    gold: string
    gray: string
    lightGray: string
    darkGray: string
    black: string
    white: string
    transparent: string
    random: () => string
}

export type Appearance = "auto" | "none"
export type AlignContent =
    | "flex-start"
    | "flex-end"
    | "center"
    | "space-between"
    | "space-around"
    | "space-evenly"
    | "stretch"
    | "initial"
    | "inherit"
export type AlignItems =
    | "flex-start"
    | "flex-end"
    | "center"
    | "baseline"
    | "stretch"
    | "initial"
    | "inherit"
export type AlignSelf =
    | "auto"
    | "flex-start"
    | "flex-end"
    | "center"
    | "baseline"
    | "stretch"
    | "initial"
    | "inherit"
export type All = "initial" | "inherit" | "unset"
export type AnimationDirection =
    | "normal"
    | "reverse"
    | "alternate"
    | "alternate-reverse"
    | "initial"
    | "inherit"
export type AnimationFillMode =
    | "none"
    | "forwards"
    | "backwards"
    | "both"
    | "initial"
    | "inherit"
export type AnimationIterationCount =
    | "infinite"
    | "number"
    | "initial"
    | "inherit"
export type AnimationPlayState = "running" | "paused" | "initial" | "inherit"
export type AnimationTimingFunction =
    | "ease"
    | "linear"
    | "ease-in"
    | "ease-out"
    | "ease-in-out"
    | "step-start"
    | "step-end"
    | "initial"
    | "inherit"
export type BackdropFilter =
    | "none"
    | "initial"
    | "inherit"
    | string
    | [Filter, string | number]
export type BackfaceVisibility = "visible" | "hidden" | "initial" | "inherit"
export type BackgroundAttachment =
    | "scroll"
    | "fixed"
    | "local"
    | "initial"
    | "inherit"
export type BackgroundBlendMode =
    | "normal"
    | "multiply"
    | "screen"
    | "overlay"
    | "darken"
    | "lighten"
    | "color-dodge"
    | "saturate"
    | "color"
    | "luminosity"
export type BackgroundClip =
    | "border-box"
    | "padding-box"
    | "content-box"
    | "initial"
    | "inherit"
export type BackgroundOrigin = BackgroundClip
export type BackgroundPosition =
    | PositionValue
    | [PositionValue, PositionValue]
    | "initial"
    | "inherit"
    | CSSTuple
export type BackgroundRepeat =
    | "repeat"
    | "repeat-x"
    | "repeat-y"
    | "no-repeat"
    | "space"
    | "round"
    | "initial"
    | "inherit"
export type BackgroundSize =
    | "auto"
    | "cover"
    | "contain"
    | "initial"
    | "inherit"
    | CSSTuple
export type BorderCollapse = "separate" | "collapse" | "initial" | "inherit"
export type BorderImageRepeat =
    | "stretch"
    | "repeat"
    | "round"
    | "space"
    | "initial"
    | "inherit"
export type BorderStyle =
    | "none"
    | "hidden"
    | "dotted"
    | "dashed"
    | "solid"
    | "double"
    | "groove"
    | "ridge"
    | "inset"
    | "outset"
    | "initial"
    | "inherit"
export type BoxSizing = "content-box" | "border-box" | "initial" | "inherit"
export type BreakBefore =
    | "auto"
    | "avoid"
    | "always"
    | "all"
    | "avoid-page"
    | "page"
    | "left"
    | "right"
    | "recto"
    | "verso"
    | "avoid-column"
    | "column"
    | "avoid-region"
    | "region"
export type BreakAfter = BreakBefore
export type BreakInside = BreakBefore
export type CaptionSide = "top" | "bottom" | "initial" | "inherit"
export type Clear = "none" | "left" | "right" | "both" | "initial" | "inherit"
export type ColumnCount = "auto" | "initial" | "inherit"
export type CSSTuple = string | [string, string]
export type FlexDirection =
    | "row"
    | "row-reverse"
    | "column"
    | "column-reverse"
    | "initial"
    | "inherit"
export type FlexWrap =
    | "nowrap"
    | "wrap"
    | "wrap-reverse"
    | "initial"
    | "inherit"
export type Float = "none" | "left" | "right" | "initial" | "inherit"
export type FontStyle = "normal" | "italic" | "oblique" | "initial" | "inherit"
export type FontVariantCaps =
    | "normal"
    | "small-caps"
    | "all-small-caps"
    | "petite-caps"
    | "all-petite-caps"
    | "unicase"
    | "titling-caps"
    | "initial"
    | "inherit"
    | "unset"
export type FontVariantPosition =
    | "normal"
    | "sub"
    | "super"
    | "initial"
    | "inherit"
export type Filter =
    | "blur"
    | "brightness"
    | "contrast"
    | "drop-shadow"
    | "grayscale"
    | "hue-rotate"
    | "invert"
    | "opacity"
    | "saturate"
    | "sepia"
    | "initial"
    | "inherit"
export type GridAutoFlow =
    | "row"
    | "column"
    | "dense"
    | "row dense"
    | "column dense"
export type Hyphens = "none" | "manual" | "auto" | "initial" | "inherit"
export type PositionValue = "left" | "right" | "top" | "bottom" | "center"
export type URL = string
export type FontSize =
    | "xx-small"
    | "x-small"
    | "small"
    | "medium"
    | "large"
    | "x-large"
    | "xx-large"
    | "smaller"
    | "larger"
    | "initial"
    | "inherit"
export type TextAlign =
    | "left"
    | "right"
    | "center"
    | "justify"
    | "initial"
    | "inherit"
export type TextDecoration =
    | "none"
    | "underline"
    | "overline"
    | "line-through"
    | "initial"
    | "inherit"
export type TextTransform =
    | "none"
    | "capitalize"
    | "uppercase"
    | "lowercase"
    | "initial"
    | "inherit"
export type TextUnderlinePosition =
    | "auto"
    | "under"
    | "left"
    | "right"
    | "initial"
    | "inherit"
export type WhiteSpace =
    | "normal"
    | "nowrap"
    | "pre"
    | "pre-line"
    | "pre-wrap"
    | "initial"
    | "inherit"
export type WordBreak =
    | "normal"
    | "break-all"
    | "keep-all"
    | "break-word"
    | "initial"
    | "inherit"
export type WordWrap = "normal" | "break-word" | "initial" | "inherit"
export type WritingMode =
    | "horizontal-tb"
    | "vertical-rl"
    | "vertical-lr"
    | "sideways-rl"
    | "sideways-lr"
export type ColumnFill = "balance" | "auto"
export type ColumnSpan = "none" | "all"
export type Direction = "ltr" | "rtl" | "initial" | "inherit"
export type EmptyCells = "show" | "hide" | "initial" | "inherit"
export type Isolation = "auto" | "isolate" | "initial" | "inherit"
export type JustifyContent =
    | "flex-start"
    | "flex-end"
    | "center"
    | "space-between"
    | "space-around"
    | "space-evenly"
    | "initial"
    | "inherit"
export type JustifyItems =
    | "auto"
    | "normal"
    | "stretch"
    | "center"
    | "start"
    | "end"
    | "flex-start"
    | "flex-end"
    | "self-start"
    | "self-end"
    | "left"
    | "right"
    | "baseline"
    | "first baseline"
    | "last baseline"
    | "safe center"
    | "unsafe center"
    | "legacy right"
    | "legacy left"
    | "legacy center"
    | "legacy stretch"
    | "initial"
    | "inherit"
export type JustifySelf = JustifyItems
export type LineBreak = "auto" | "loose" | "normal" | "strict" | "anywhere"
export type ImageRendering = "auto" | "crisp-edges" | "pixelated"
export type ListStylePosition = "inside" | "outside" | "initial" | "inherit"
export type MaskBorderMode = "alpha" | "luminance"
export type ObjectFit = "fill" | "contain" | "cover" | "none" | "scale-down"
export type MixBlendMode =
    | "normal"
    | "multiply"
    | "screen"
    | "overlay"
    | "darken"
    | "lighten"
    | "color-dodge"
    | "color-burn"
    | "hard-light"
    | "soft-light"
    | "difference"
    | "exclusion"
    | "hue"
    | "saturation"
    | "color"
    | "luminosity"
export type Overflow =
    | "visible"
    | "hidden"
    | "scroll"
    | "auto"
    | "initial"
    | "inherit"
export type OverflowAnchor = "none" | "auto"
export type OverflowWrap = "normal" | "break-word" | "anywhere"
export type OverflowX =
    | "visible"
    | "hidden"
    | "scroll"
    | "auto"
    | "initial"
    | "inherit"
export type OverflowY =
    | "visible"
    | "hidden"
    | "scroll"
    | "auto"
    | "initial"
    | "inherit"
export type OverscrollBehavior = "auto" | "contain" | "none"
export type PointerEvents = "auto" | "none" | "initial" | "inherit"
export type Position = "static" | "relative" | "absolute" | "fixed" | "sticky"
export type Resize =
    | "none"
    | "both"
    | "horizontal"
    | "vertical"
    | "initial"
    | "inherit"
export type ScrollBehavior = "auto" | "smooth"
export type ScrollSnapStop = "normal" | "always"
export type TableLayout = "auto" | "fixed" | "initial" | "inherit"
export type TextAlignLast =
    | "auto"
    | "left"
    | "right"
    | "center"
    | "justify"
    | "start"
    | "end"
export type TextCombineUpright =
    | "none"
    | "all"
    | "digits"
    | "initial"
    | "inherit"
export type TextJustify =
    | "auto"
    | "inter-word"
    | "inter-ideograph"
    | "inter-cluster"
    | "distribute"
export type TextOrientation =
    | "mixed"
    | "upright"
    | "sideways"
    | "sideways-right"
    | "use-glyph-orientation"
export type TextRendering =
    | "auto"
    | "optimizeSpeed"
    | "optimizeLegibility"
    | "geometricPrecision"
export type UnicodeBidi =
    | "normal"
    | "embed"
    | "isolate"
    | "bidi-override"
    | "isolate-override"
    | "plaintext"
export type UserSelect = "auto" | "text" | "none" | "contain" | "all"
export type VerticalAlign =
    | "baseline"
    | "length"
    | "sub"
    | "super"
    | "top"
    | "text-top"
    | "middle"
    | "bottom"
    | "text-bottom"
    | "initial"
    | "inherit"
export type Visibility =
    | "visible"
    | "hidden"
    | "collapse"
    | "initial"
    | "inherit"
export type OutlineStyle =
    | "none"
    | "hidden"
    | "dotted"
    | "dashed"
    | "solid"
    | "double"
    | "groove"
    | "ridge"
    | "inset"
    | "outset"
    | "initial"
    | "inherit"
export type TextOverflow = "clip" | "ellipsis" | "initial" | "inherit"
export type TouchAction = "auto" | "none" | "pan-x" | "pan-y" | "manipulation"
export type TransformBox = "border-box" | "fill-box" | "view-box"
export type TransformStyle = "flat" | "preserve-3d"
export type FontKerning = "auto" | "normal" | "none"
export type Display =
    | "inline"
    | "block"
    | "contents"
    | "flex"
    | "grid"
    | "inline-block"
    | "inline-flex"
    | "inline-grid"
    | "inline-table"
    | "list-item"
    | "run-in"
    | "table"
    | "table-caption"
    | "table-column-group"
    | "table-header-group"
    | "table-footer-group"
    | "table-row-group"
    | "table-cell"
    | "table-column"
    | "table-row"
    | "none"
    | "initial"
    | "inherit"
export type Cursor =
    | "auto"
    | "default"
    | "none"
    | "context-menu"
    | "help"
    | "pointer"
    | "progress"
    | "wait"
    | "cell"
    | "crosshair"
    | "text"
    | "vertical-text"
    | "alias"
    | "copy"
    | "move"
    | "no-drop"
    | "not-allowed"
    | "e-resize"
    | "n-resize"
    | "ne-resize"
    | "nw-resize"
    | "s-resize"
    | "se-resize"
    | "sw-resize"
    | "w-resize"
    | "ew-resize"
    | "ns-resize"
    | "nesw-resize"
    | "nwse-resize"
    | "col-resize"
    | "row-resize"
    | "all-scroll"
    | "zoom-in"
    | "zoom-out"
    | "grab"
    | "grabbing"
    | "initial"
    | "inherit"
export type Flex =
    | "none"
    | "initial"
    | "inherit"
    | "auto"
    | FlexGrow
    | FlexShrink
    | FlexBasis
    | [FlexGrow, FlexShrink, FlexBasis]
export type FlexGrow = string
export type FlexShrink = string
export type FlexBasis = "auto" | "initial" | "inherit" | "content" | string
export type ListStyleType =
    | "none"
    | "disc"
    | "circle"
    | "square"
    | "decimal"
    | "decimal-leading-zero"
    | "lower-roman"
    | "upper-roman"
    | "lower-greek"
    | "lower-latin"
    | "upper-latin"
    | "armenian"
    | "georgian"
    | "lower-alpha"
    | "upper-alpha"
    | "none"
    | "initial"
    | "inherit"
export type MaskMode =
    | "alpha"
    | "luminance"
    | "match-source"
    | "initial"
    | "inherit"
export type MaskOrigin =
    | "border-box"
    | "padding-box"
    | "content-box"
    | "margin-box"
    | "fill-box"
    | "stroke-box"
    | "view-box"
    | "initial"
    | "inherit"
export type MaskPosition = CSSTuple | "initial" | "inherit"
export type MaskRepeat =
    | "repeat"
    | "no-repeat"
    | "repeat-x"
    | "repeat-y"
    | "initial"
    | "inherit"
    | "round"
    | "space"
export type MaskSize =
    | "auto"
    | "cover"
    | "contain"
    | "initial"
    | "inherit"
    | string
export type PageBreak =
    | "auto"
    | "avoid"
    | "always"
    | "left"
    | "right"
    | "initial"
    | "inherit"
export type PlaceContent =
    | "normal"
    | "stretch"
    | "center"
    | "start"
    | "end"
    | "space-between"
    | "space-around"
    | "space-evenly"
    | "safe"
    | "unsafe"
    | "initial"
    | "inherit"
export type PlaceItems =
    | "normal legacy"
    | "baseline"
    | "center"
    | "end"
    | "start"
    | "stretch"
    | "initial"
    | "inherit"
export type PlaceSelf =
    | "auto"
    | "normal"
    | "center"
    | "end"
    | "start"
    | "stretch"
    | "initial"
    | "inherit"
    | "right"
    | "left"
    | "safe"
    | "unsafe"
    | "initial"
    | "inherit"

export type State = { [key: string]: any }
