name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
        
      - name: Install dependencies with Bun
        run: bun install

      - name: Build the package with Bun
        run: bun run build

      - name: Publish to NPM
        run: bun run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
